// cart
export const ADD_CART = 'ADD_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const UPDATE_QUANTITY_PRODUCT_IN_CART = 'UPDATE_QUANTITY_PRODUCT_IN_CART';
export const ADD_QUANTITY_PRODUCT_IN_CART = 'ADD_QUANTITY_PRODUCT_IN_CART';
export const MINUS_QUANTITY_PRODUCT_IN_CART = 'MINUS_QUANTITY_PRODUCT_IN_CART';

// auth 
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const EMPTY_ERROR_MESSAGE = 'EMPTY_ERROR_MESSAGE';

// user
export const LIKE_PRODUCT = 'LIKE_PRODUCT';
export const UNLIKE_PRODUCT = 'UNLIKE_PRODUCT';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';